alias ls='ls --color --group-directories-first'
alias grep='grep --color'

alias l='ls -lp'
alias ll='ls -lpa'

alias ..='cd ..'
alias ~='cd'
alias ...='cd ../..'
alias ....='cd ../..'

alias g='git'
alias gs='git status'
alias ga='git add'
alias gaa='git add .'
alias ga.='git add .'
alias gc='git commit'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gcm='git checkout master'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gsts='git stash save'
alias gstp='git stash pop'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gm='git merge'
alias gmm='git merge master'
alias gmt='git mergetool'
alias gd='git diff'
alias gdc='git diff --cached'
alias go='start $(git remote get-url origin)'
alias gp='git push'
alias gpsup=' git push --set-upstream origin $(git branch --show-current)'
alias gl='git pull'
alias gpull='git pull'
alias gpush='git push'
alias glog='git log --graph --pretty"=%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset"'
alias glogn='git log --graph --pretty"=%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" -n'
alias grs='git reset'
alias gchp='git cherry-pick'

alias config='git --git-dir=$HOME/dotWindows.git/ --work-tree=$HOME' 

alias dc='docker-compose'

alias vimbash='vim ~/.bashrc'

alias vs='devenv'
alias vssln='devenv **/*.sln &'

alias man='~/.bin/man.sh'

alias task='wsl task'
